### ISSUE TITLE
Add hsc2hs source to snippets

### ISSUE THREAD

**Issue by SX91** [atom-haskell/language-haskell#97]
`'.source.haskell':` should be `'.source.haskell, .source.hsc2hs':`.

You could also add more useful snippets like:
```
'.source.haskell, .source.hsc2hs, source.c2hs':
  'INLINE':
    'prefix': 'inl'
    'body': '{-# INLINE ${1:function} #-}'
  'NOINLINE':
    'prefix': 'noinl'
    'body': '{-# NOINLINE ${1:function} #-}'
  'INLINABLE':
    'prefix': 'inlinable'
    'body': '{-# INLINABLE ${1:function} #-}'
  'LANGUAGE':
    'prefix': 'lang'
    'body': '{-# LANGUAGE ${1:ext} #-}'
  'UNPACK':
    'prefix': 'unpack'
    'body': '{-# UNPACK #-} '
  'OPTIONS_GHC':
    'prefix': 'ghc'
    'body': '{-# OPTIONS_GHC -${1:option} #-}'

'.source.cabal':
  'executable':
    'prefix': 'exec'
    'body': '''
      executable ${1:appname}
          main-is: Main.hs
          build-depends:
              base >=4 && <5,
              ${2:libname}
          default-language: Haskell2010
          hs-source-dirs: App
          ghc-options: -Wall -threaded -rtsopts
      '''
```
